name: Publish package to npm

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deps:
    name: Install dependencies
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - run: yarn install --frozen-lockfile

      - uses: actions/cache/save@v4
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-${{ github.sha }}

  build:
    name: Build
    needs: [deps]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: node_modules/
          key: ${{ runner.os }}-node-${{ github.sha }}

      - run: npm run build

      - uses: actions/cache/save@v4
        with:
          path: dist/
          key: ${{ runner.os }}-build-${{ github.sha }}

  # exports-check:
  #   name: Check exports
  #   needs: [deps, build]
  #   runs-on: ubuntu-24.04
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version-file: .node-version

  #     - name: Restore node_modules from cache
  #       uses: actions/cache/restore@v4
  #       with:
  #         fail-on-cache-miss: true
  #         path: node_modules/
  #         key: ${{ runner.os }}-node-${{ github.sha }}

  #     - name: Restore build from cache
  #       uses: actions/cache/restore@v4
  #       with:
  #         fail-on-cache-miss: true
  #         path: dist/
  #         key: ${{ runner.os }}-build-${{ github.sha }}

  #     - run: npm run exports-check

  test:
    name: Test
    needs: [deps]
    uses: ./.github/workflows/base-x.yml
    with:
      command: npm run test

  lint:
    name: Lint
    needs: [deps]
    uses: ./.github/workflows/base-x.yml
    with:
      command: npm run lint

  format-check:
    name: Check format
    needs: [deps]
    uses: ./.github/workflows/base-x.yml
    with:
      command: npm run format-check

  spelling-check:
    name: Check spelling
    needs: [deps]
    uses: ./.github/workflows/base-x.yml
    with:
      command: npm run spelling-check

  deploy:
    name: Publish
    runs-on: ubuntu-24.04
    needs: [build, test, lint]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org

      - uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: dist/
          key: ${{ runner.os }}-build-${{ github.sha }}

      - run: npm pkg delete scripts devDependencies

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
